# Generated by Django 5.2.5 on 2025-10-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rms_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="dummy_field",
            field=models.BooleanField(default=False),
        ),
    ]
