# Generated by Django 5.2.4 on 2025-10-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rms_app", "0002_request_dummy_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="doj",
            field=models.DateField(blank=True, null=True),
        ),
    ]
